{{- if eq .Values.rabbitmq.ingress.ingressClassName "traefik" }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-rabbitmq
  namespace: kube-system
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - {{ .Values.rabbitmq.ingress.path }}
{{- end }}
