rabbitmq:
  auth:
    password: "password"
    securePassword: false
  ingress:
    enabled: true
    # ingressClassName: 'traefik'/'nginx'
    # path: /rabbitmq #traefik
    # annotations:
    #   traefik.ingress.kubernetes.io/router.middlewares: kube-system-strip-prefix-rabbitmq@kubernetescrd
    # path: /rabbitmq(/|$)(.*) #nginx
    # annotations:
    #   nginx.ingress.kubernetes.io/rewrite-target: /$2
    tls: false
    selfSigned: false
